/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package login.Student.Details;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author User
 */
public class ChangePassword extends javax.swing.JFrame {

    private static class pubpublic {

        public pubpublic() {
        }
    }

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPwChange = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtold = new javax.swing.JPasswordField();
        txtnew = new javax.swing.JPasswordField();
        txtcon = new javax.swing.JPasswordField();
        lblChgUser = new javax.swing.JLabel();
        txtchguser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                open(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(106, 11, 188, 29);

        jLabel3.setText("Old Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 90, 14);

        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 90, 14);

        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 110, 14);

        btnPwChange.setText("Change");
        btnPwChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPwChangeActionPerformed(evt);
            }
        });
        getContentPane().add(btnPwChange);
        btnPwChange.setBounds(230, 310, 80, 23);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 310, 80, 23);

        jLabel6.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);
        getContentPane().add(txtold);
        txtold.setBounds(190, 170, 130, 20);
        getContentPane().add(txtnew);
        txtnew.setBounds(190, 210, 130, 20);
        getContentPane().add(txtcon);
        txtcon.setBounds(190, 250, 130, 20);

        lblChgUser.setText("User Name");
        getContentPane().add(lblChgUser);
        lblChgUser.setBounds(20, 130, 70, 14);

        txtchguser.setEditable(false);
        getContentPane().add(txtchguser);
        txtchguser.setBounds(190, 130, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPwChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPwChangeActionPerformed
        // TODO add your handling code here:

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_information", "root", "123");
            Statement stm = conn.createStatement();// for login
            String qry = "select password from login where username = '" + txtchguser.getText() + "';  ";
            ResultSet rst = stm.executeQuery(qry);

            if (rst.next() && !(txtold.getText().equals(rst.getString("password")))) {

                JOptionPane.showMessageDialog(this, "Invalid Existing Password", "Old Password Error", WIDTH);
            } else {

                if (!(txtnew.getText().equals(txtcon.getText()))) {

                    JOptionPane.showMessageDialog(this, "Password doesn't match", "New Password Error", WIDTH);
                } else if (txtnew.getText().equals("")) {

                    JOptionPane.showMessageDialog(this, "Please enter new Password");
                } else {

                    Statement stm2 = conn.createStatement(); // for login
                    String qry2 = "update login set password = '" + txtnew.getText() + "' where username = '" + txtchguser.getText() + "';  ";
                    int result = stm2.executeUpdate(qry2);

                    Statement stm3 = conn.createStatement();
                    String qry3 = "update Admin set password = '" + txtnew.getText() + "' where username = '" + txtchguser.getText() + "' ; ";
                    int result2 = stm3.executeUpdate(qry3);

                    if (result == 1 && result2 == 1) {

                        JOptionPane.showMessageDialog(this, "Password Changed", "Message", WIDTH);
                        txtold.setText("");
                        txtnew.setText("");
                        txtcon.setText("");
                    } else {

                        JOptionPane.showMessageDialog(this, "Cannot Change the Password", "Error", WIDTH);
                    }
                }
            }


        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "invalid");
        }



    }//GEN-LAST:event_btnPwChangeActionPerformed

    private void open(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_open
        // TODO add your handling code here:
    }//GEN-LAST:event_open

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPwChange;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblChgUser;
    public javax.swing.JTextField txtchguser;
    private javax.swing.JPasswordField txtcon;
    private javax.swing.JPasswordField txtnew;
    private javax.swing.JPasswordField txtold;
    // End of variables declaration//GEN-END:variables
}
